version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  location:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./location.conf:/etc/nginx/conf.d/default.conf
  proxy:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
  header:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./header.conf:/etc/nginx/conf.d/default.conf
  dynamic-static:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./dynamic-static-separation.conf:/etc/nginx/conf.d/default.conf
  load-balance:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./load-balance.conf:/etc/nginx/conf.d/default.conf
  request-filter:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./request-filter.conf:/etc/nginx/conf.d/default.conf
  cors:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./cors.conf:/etc/nginx/conf.d/default.conf